sudo: required

services:
  - docker

before_install:
  - make build

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: "make push"
    on:
      branch: master
