sudo: required

services:
  - docker

before_install:
  - make build

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    script: "make push"
    on:
      branch: master
