name: root

dependencies:
    - ipython
    - numpy
    - pandas
    - matplotlib
    - requests
    - scipy
    - scikit-learn
    - joblib
    - nltk
    - jupyter
    - pip:
        - nbbrowserpdf
        - jupyter_contrib_nbextensions
        - yapf
